import type { Metadata } from "next";
import { Geist, Geist_Mono, Exo, Outfit, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"]
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"]
})

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "BetterDiens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${exo.variable} ${roboto.variable} ${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
